<?php

namespace App\Models;

use DateTime;
use Illuminate\Database\Eloquent\Model;

class Functions extends Model
{

    public const DEGREES = [
        "AA" => "Associate Degree",
        "BA" => 'Bachelor\'s Degree',
        "MA" => 'Master\'s Degree',
        "PhD" => "Doctorate Degree (Ph.D.)",
        "GC" => "Graduate Certificate",
        "DIP" => "Diploma",
    ];
    public const CATEGORY = [
        "frontend" => "Frontend",
        "backend" => 'Backend',
        "other" => 'Other',
    ];
    const COUNTRIES = [
        "United States" => "us",
        "Afghanistan" => "af",
        "Albania" => "al",
        "Algeria" => "dz",
        "American Samoa" => "as",
        "Andorra" => "ad",
        "Angola" => "ad",
        "Anguilla" => "ai",
        "Antarctica" => "aq",
        "Antigua and Barbuda" => "ag",
        "Argentina" => "ar",
        "Armenia" => "am",
        "Aruba" => "aw",
        "Australia" => "au",
        "Austria" => "at",
        "Azerbaijan" => "az",
        "Bahamas" => "bs",
        "Bahrain" => "bh",
        "Bangladesh" => "bd",
        "Barbados" => "bb",
        "Belarus" => "by",
        "Belgium" => "be",
        "Belize" => "bz",
        "Benin" => "bj",
        "Bermuda" => "bm",
        "Bhutan" => "bt",
        "Bolivia" => "bo",
        "Bosnia and Herzegowina" => "ba",
        "Botswana" => "bw",
        "Bouvet Island" => "bv",
        "Brazil" => "br",
        "British Indian Ocean Territory" => "io",
        "Brunei Darussalam" => "bn",
        "Bulgaria" => "bg",
        "Burkina Faso" => "bf",
        "Burundi" => "bi",
        "Cambodia" => "kh",
        "Cameroon" => "cm",
        "Canada" => "ca",
        "Cabo Verde" => "cv",
        "Cayman Islands" => "ky",
        "Central African Republic" => "cf",
        "Chad" => "td",
        "Chile" => "cl",
        "China" => "cn",
        "Christmas Island" => "cx",
        "Cocos (Keeling) Islands" => "cc",
        "Colombia" => "co",
        "Comoros" => "km",
        "Congo" => "cg",
        "Congo, the Democratic Republic of the" => "cd",
        "Cook Islands" => "ck",
        "Costa Rica" => "cr",
        "Cote d'Ivoire" => "ci",
        "Croatia (Hrvatska)" => "hr",
        "Cuba" => "cu",
        "Cyprus" => "cy",
        "Czech Republic" => "cz",
        "Denmark" => "dk",
        "Djibouti" => "dj",
        "Dominica" => "dm",
        "Dominican Republic" => "do",
        "East Timor" => "tl",
        "Ecuador" => "ec",
        "Egypt" => "eg",
        "El Salvador" => "sv",
        "Equatorial Guinea" => "gq",
        "Eritrea" => "er",
        "Estonia" => "ee",
        "Ethiopia" => "et",
        "Falkland Islands (Malvinas)" => "fk",
        "Faroe Islands" => "fo",
        "Fiji" => "fj",
        "Finland" => "fi",
        "France" => "fr",
        "French Guiana" => "gf",
        "French Polynesia" => "pf",
        "French Southern Territories" => "tf",
        "Gabon" => "ga",
        "Gambia" => "gm",
        "Georgia" => "ge",
        "Germany" => "de",
        "Ghana" => "gh",
        "Gibraltar" => "gi",
        "Greece" => "gr",
        "Greenland" => "gl",
        "Grenada" => "gd",
        "Guadeloupe" => "gp",
        "Guam" => "gu",
        "Guatemala" => "gt",
        "Guinea" => "gn",
        "Guinea-Bissau" => "gw",
        "Guyana" => "gy",
        "Haiti" => "ht",
        "Heard and Mc Donald Islands" => "hm",
        "Holy See (Vatican City State)" => "va",
        "Honduras" => "hn",
        "Hong Kong" => "hk",
        "Hungary" => "hu",
        "Iceland" => "is",
        "India" => "in",
        "Indonesia" => "id",
        "Iran (Islamic Republic of)" => "ir",
        "Iraq" => "iq",
        "Ireland" => "ie",
        "Israel" => "il",
        "Italy" => "it",
        "Jamaica" => "jm",
        "Japan" => "jp",
        "Jordan" => "jo",
        "Kazakhstan" => "kz",
        "Kenya" => "ke",
        "Kiribati" => "ki",
        "Korea, Democratic People's Republic of" => "kp",
        "Korea, Republic of" => "kr",
        "Kuwait" => "kw",
        "Kyrgyzstan" => "kg",
        "Lao, People's Democratic Republic" => "la",
        "Latvia" => "lv",
        "Lebanon" => "lb",
        "Lesotho" => "ls",
        "Liberia" => "lr",
        "Libyan Arab Jamahiriya" => "ly",
        "Liechtenstein" => "li",
        "Lithuania" => "lt",
        "Luxembourg" => "lu",
        "Macao" => "mo",
        "Macedonia, The Former Yugoslav Republic of" => "mk",
        "Madagascar" => "mg",
        "Malawi" => "mw",
        "Malaysia" => "my",
        "Maldives" => "mv",
        "Mali" => "ml",
        "Malta" => "mt",
        "Marshall Islands" => "mh",
        "Martinique" => "mq",
        "Mauritania" => "mr",
        "Mauritius" => "mu",
        "Mayotte" => "yt",
        "Mexico" => "mx",
        "Micronesia, Federated States of" => "fm",
        "Moldova, Republic of" => "md",
        "Monaco" => "mc",
        "Mongolia" => "mn",
        "Montserrat" => "ms",
        "Morocco" => "ma",
        "Mozambique" => "mz",
        "Myanmar" => "mm",
        "Namibia" => "na",
        "Nauru" => "nr",
        "Nepal" => "np",
        "Netherlands" => "nl",
        "Netherlands Antilles" => "an",
        "New Caledonia" => "nc",
        "New Zealand" => "nz",
        "Nicaragua" => "ni",
        "Niger" => "ne",
        "Nigeria" => "ng",
        "Niue" => "nu",
        "Norfolk Island" => "nf",
        "Northern Mariana Islands" => "mp",
        "Norway" => "no",
        "Oman" => "om",
        "Pakistan" => "pk",
        "Palau" => "pw",
        "Panama" => "pa",
        "Papua New Guinea" => "pg",
        "Paraguay" => "py",
        "Peru" => "pe",
        "Philippines" => "ph",
        "Pitcairn" => "pn",
        "Poland" => "pl",
        "Portugal" => "pt",
        "Puerto Rico" => "pr",
        "Qatar" => "qa",
        "Reunion" => "re",
        "Romania" => "ro",
        "Russian Federation" => "ru",
        "Rwanda" => "rw",
        "Saint Kitts and Nevis" => "kn",
        "Saint Lucia" => "lc",
        "Saint Vincent and the Grenadines" => "vc",
        "Samoa" => "ws",
        "San Marino" => "sm",
        "Sao Tome and Principe" => "st",
        "Saudi Arabia" => "sa",
        "Senegal" => "sn",
        "Seychelles" => "sc",
        "Sierra Leone" => "sl",
        "Singapore" => "sg",
        "Slovakia (Slovak Republic)" => "sk",
        "Slovenia" => "si",
        "Solomon Islands" => "sb",
        "Somalia" => "so",
        "South Africa" => "za",
        "South Georgia and the South Sandwich Islands" => "gs",
        "Spain" => "es",
        "Sri Lanka" => "lk",
        "St. Helena" => "sh",
        "St. Pierre and Miquelon" => "pm",
        "Sudan" => "sd",
        "Suriname" => "sr",
        "Svalbard and Jan Mayen Islands" => "sj",
        "Swaziland" => "sz",
        "Sweden" => "se",
        "Switzerland" => "ch",
        "Syrian Arab Republic" => "sy",
        "Taiwan, Province of China" => "tw",
        "Tajikistan" => "tj",
        "Tanzania, United Republic of" => "tz",
        "Thailand" => "th",
        "Togo" => "tg",
        "Tokelau" => "tk",
        "Tonga" => "to",
        "Trinidad and Tobago" => "tt",
        "Tunisia" => "tn",
        "Turkey" => "tr",
        "Turkmenistan" => "tm",
        "Turks and Caicos Islands" => "tc",
        "Tuvalu" => "tv",
        "Uganda" => "ug",
        "Ukraine" => "ua",
        "United Arab Emirates" => "ae",
        "United Kingdom" => "gb",
        "United States Minor Outlying Islands" => "um",
        "Uruguay" => "uy",
        "Uzbekistan" => "uz",
        "Vanuatu" => "vu",
        "Venezuela" => "ve",
        "Vietnam" => "vn",
        "Virgin Islands (British)" => "vg",
        "Virgin Islands (U.S.)" => "vi",
        "Wallis and Futuna Islands" => "wf",
        "Western Sahara" => "eh",
        "Yemen" => "ye",
        "Serbia" => "yu",
        "Zambia" => "zm",
        "Zimbabwe" => "zw",
    ];
    const EUROPEAN_STATES = [
        "albania" => "Albania",
        "andorra" => "Andorra",
        "austria" => "Austria",
        "belarus" => "Belarus",
        "belgium" => "Belgium",
        "bosnia_and_herzegovina" => "Bosnia and Herzegovina",
        "bulgaria" => "Bulgaria",
        "croatia" => "Croatia",
        "cyprus" => "Cyprus",
        "czech_republic" => "Czech Republic",
        "denmark" => "Denmark",
        "estonia" => "Estonia",
        "finland" => "Finland",
        "france" => "France",
        "germany" => "Germany",
        "greece" => "Greece",
        "hungary" => "Hungary",
        "iceland" => "Iceland",
        "ireland" => "Ireland",
        "italy" => "Italy",
        "kosovo" => "Kosovo",
        "latvia" => "Latvia",
        "liechtenstein" => "Liechtenstein",
        "lithuania" => "Lithuania",
        "luxembourg" => "Luxembourg",
        "malta" => "Malta",
        "moldova" => "Moldova",
        "monaco" => "Monaco",
        "montenegro" => "Montenegro",
        "netherlands" => "Netherlands",
        "north_macedonia" => "North Macedonia",
        "norway" => "Norway",
        "poland" => "Poland",
        "portugal" => "Portugal",
        "romania" => "Romania",
        "russia" => "Russia",
        "san_marino" => "San Marino",
        "serbia" => "Serbia",
        "slovakia" => "Slovakia",
        "slovenia" => "Slovenia",
        "spain" => "Spain",
        "sweden" => "Sweden",
        "switzerland" => "Switzerland",
        "ukraine" => "Ukraine",
        "united_kingdom" => "United Kingdom",
        "vatican_city" => "Vatican City",
    ];

        const ASIAN_STATES = [
        "afghanistan" => "Afghanistan",
        "armenia" => "Armenia",
        "azerbaijan" => "Azerbaijan",
        "bahrain" => "Bahrain",
        "bangladesh" => "Bangladesh",
        "bhutan" => "Bhutan",
        "brunei" => "Brunei",
        "cambodia" => "Cambodia",
        "china" => "China",
        "cyprus" => "Cyprus",
        "east_timor" => "East Timor",
        "georgia" => "Georgia",
        "india" => "India",
        "indonesia" => "Indonesia",
        "iran" => "Iran",
        "iraq" => "Iraq",
        "israel" => "Israel",
        "japan" => "Japan",
        "jordan" => "Jordan",
        "kazakhstan" => "Kazakhstan",
        "kuwait" => "Kuwait",
        "kyrgyzstan" => "Kyrgyzstan",
        "laos" => "Laos",
        "lebanon" => "Lebanon",
        "malaysia" => "Malaysia",
        "maldives" => "Maldives",
        "mongolia" => "Mongolia",
        "myanmar" => "Myanmar",
        "nepal" => "Nepal",
        "north_korea" => "North Korea",
        "oman" => "Oman",
        "pakistan" => "Pakistan",
        "palestine" => "Palestine",
        "philippines" => "Philippines",
        "qatar" => "Qatar",
        "russia" => "Russia",
        "saudi_arabia" => "Saudi Arabia",
        "singapore" => "Singapore",
        "south_korea" => "South Korea",
        "sri_lanka" => "Sri Lanka",
        "syria" => "Syria",
        "taiwan" => "Taiwan",
        "tajikistan" => "Tajikistan",
        "thailand" => "Thailand",
        "turkey" => "Turkey",
        "turkmenistan" => "Turkmenistan",
        "united_arab_emirates" => "United Arab Emirates",
        "uzbekistan" => "Uzbekistan",
        "vietnam" => "Vietnam",
        "yemen" => "Yemen"
        ];


    const EMPLOYMENT = [
        "full-time" => "Full-time",
        "part-time" => "Part-time",
        "contract" => "Contract",
        "temporary" => "Temporary",
        "internship" => "Internship",
        "freelance" => "Freelance",
    ];

    const NORTH_AMERICAN_STATES = [
    "AL" => "Alabama",
    "AK" => "Alaska",
    "AZ" => "Arizona",
    "AR" => "Arkansas",
    "CA" => "California",
    "CO" => "Colorado",
    "CT" => "Connecticut",
    "DE" => "Delaware",
    "FL" => "Florida",
    "GA" => "Georgia",
    "HI" => "Hawaii",
    "ID" => "Idaho",
    "IL" => "Illinois",
    "IN" => "Indiana",
    "IA" => "Iowa",
    "KS" => "Kansas",
    "KY" => "Kentucky",
    "LA" => "Louisiana",
    "ME" => "Maine",
    "MD" => "Maryland",
    "MA" => "Massachusetts",
    "MI" => "Michigan",
    "MN" => "Minnesota",
    "MS" => "Mississippi",
    "MO" => "Missouri",
    "MT" => "Montana",
    "NE" => "Nebraska",
    "NV" => "Nevada",
    "NH" => "New Hampshire",
    "NJ" => "New Jersey",
    "NM" => "New Mexico",
    "NY" => "New York",
    "NC" => "North Carolina",
    "ND" => "North Dakota",
    "OH" => "Ohio",
    "OK" => "Oklahoma",
    "OR" => "Oregon",
    "PA" => "Pennsylvania",
    "RI" => "Rhode Island",
    "SC" => "South Carolina",
    "SD" => "South Dakota",
    "TN" => "Tennessee",
    "TX" => "Texas",
    "UT" => "Utah",
    "VT" => "Vermont",
    "VA" => "Virginia",
    "WA" => "Washington",
    "WV" => "West Virginia",
    "WI" => "Wisconsin",
    "WY" => "Wyoming",
    "AB" => "Alberta",
    "BC" => "British Columbia",
    "MB" => "Manitoba",
    "NB" => "New Brunswick",
    "NL" => "Newfoundland and Labrador",
    "NS" => "Nova Scotia",
    "NT" => "Northwest Territories",
    "NU" => "Nunavut",
    "ON" => "Ontario",
    "PE" => "Prince Edward Island",
    "QC" => "Quebec",
    "SK" => "Saskatchewan",
    "YT" => "Yukon",
    ];

    const SOUTH_AMERICAN_STATES = [
        "Argentina" => "Argentina",
        "Bolivia" => "Bolivia",
        "Brazil" => "Brazil",
        "Chile" => "Chile",
        "Colombia" => "Colombia",
        "Ecuador" => "Ecuador",
        "Guyana" => "Guyana",
        "Paraguay" => "Paraguay",
        "Peru" => "Peru",
        "Suriname" => "Suriname",
        "Uruguay" => "Uruguay",
        "Venezuela" => "Venezuela"
    ];

    const AFRICAN_STATES = [
        "Algeria" => "Algeria",
        "Angola" => "Angola",
        "Benin" => "Benin",
        "Botswana" => "Botswana",
        "Burkina Faso" => "Burkina Faso",
        "Burundi" => "Burundi",
        "Cabo Verde" => "Cabo Verde",
        "Cameroon" => "Cameroon",
        "Central African Republic" => "Central African Republic",
        "Chad" => "Chad",
        "Comoros" => "Comoros",
        "Democratic Republic of the Congo" => "Democratic Republic of the Congo",
        "Republic of the Congo" => "Republic of the Congo",
        "Djibouti" => "Djibouti",
        "Egypt" => "Egypt",
        "Equatorial Guinea" => "Equatorial Guinea",
        "Eritrea" => "Eritrea",
        "Eswatini" => "Eswatini",
        "Ethiopia" => "Ethiopia",
        "Gabon" => "Gabon",
        "Gambia" => "Gambia",
        "Ghana" => "Ghana",
        "Guinea" => "Guinea",
        "Guinea-Bissau" => "Guinea-Bissau",
        "Ivory Coast" => "Ivory Coast",
        "Kenya" => "Kenya",
        "Lesotho" => "Lesotho",
        "Liberia" => "Liberia",
        "Libya" => "Libya",
        "Madagascar" => "Madagascar",
        "Malawi" => "Malawi",
        "Mali" => "Mali",
        "Mauritania" => "Mauritania",
        "Mauritius" => "Mauritius",
        "Morocco" => "Morocco",
        "Mozambique" => "Mozambique",
        "Namibia" => "Namibia",
        "Niger" => "Niger",
        "Nigeria" => "Nigeria",
        "Rwanda" => "Rwanda",
        "Sao Tome and Principe" => "Sao Tome and Principe",
        "Senegal" => "Senegal",
        "Seychelles" => "Seychelles",
        "Sierra Leone" => "Sierra Leone",
        "Somalia" => "Somalia",
        "South Africa" => "South Africa",
        "South Sudan" => "South Sudan",
        "Sudan" => "Sudan",
        "Tanzania" => "Tanzania",
        "Togo" => "Togo",
        "Tunisia" => "Tunisia",
        "Uganda" => "Uganda",
        "Zambia" => "Zambia",
        "Zimbabwe" => "Zimbabwe"
    ];

    const AUSTRALIAN_STATES = [
        "ACT" => "Australian Capital Territory",
        "NSW" => "New South Wales",
        "NT" => "Northern Territory",
        "QLD" => "Queensland",
        "SA" => "South Australia",
        "TAS" => "Tasmania",
        "VIC" => "Victoria",
        "WA" => "Western Australia",
    ];


    const MIN_YEARS_OF_EXPERIENCE = 1;
    const MAX_YEARS_OF_EXPERIENCE = 50;

    const FRONTEND_FRAMEWORKS = [
        "vue" => "Vue.js",
        "react" => "React.js",
        "angular" => "Angular.js",
        "ember" => "Ember.js",
        "backbone" => "Backbone.js",
        "knockout" => "Knockout.js",
        "svelte" => "Svelte.js",
        "jquery" => "jQuery",
        "bootstrap" => "Bootstrap",
        "foundation" => "Foundation",
        "bulma" => "Bulma",
        "tailwind css" => "Tailwind CSS",
        "semantic" => "Semantic UI",
        "materialize" => "Materialize",
        "material" => "Material Design Lite",
        "next" => "Next.js",
        "nuxt" => "Nuxt.js",
        "gatsby" => "Gatsby",
        "grid" => "CSS Grid",
        "flexbox" => "Flexbox",
        "ionic" => "Ionic",
        "quasar" => "Quasar",
        "vuetify" => "Vuetify",
    ];
    const BACKEND_FRAMEWORKS = [
        "laravel" => "Laravel",
        "django" => "Django",
        "express" => "Express",
        "spring" => "Spring",
        "ruby_on_rails" => "Ruby on Rails",
        "asp_net" => "ASP.NET",
        "symfony" => "Symfony",
        "codeigniter" => "CodeIgniter",
        "yii" => "Yii",
        "cakephp" => "CakePHP",
        "flask" => "Flask",
        "phalcon" => "Phalcon",
        "node" => "Node.js",
        "koa" => "Koa",
        "fastify" => "Fastify",
        "slim" => "Slim",
        "lumen" => "Lumen",
        "sails" => "Sails.js",
        "adonis" => "AdonisJS",
        "phoenix" => "Phoenix",
        "grails" => "Grails",
        "jhipster" => "JHipster",
        "play" => "Play",
        "vert_x" => "Vert.x",
        "rocket" => "Rocket",
    ];
    const LANGUAGES = [
        "html" => "Html",
        "css" => "Css",
        "javascript" => "JavaScript",
        "php" => "PHP",
        "python" => "Python",
        "java" => "Java",
        "c#" => "C#",
        "c++" => "C++",
        "ruby" => "Ruby",
        "swift" => "Swift",
        "typescript" => "TypeScript",
        "rust" => "Rust",
        "go" => "Go",
        "kotlin" => "Kotlin",
        "scala" => "Scala",
        "dart" => "Dart",
        "r" => "R",
        "perl" => "Perl",
        "elixir" => "Elixir",
        "clojure" => "Clojure",
        "haskell" => "Haskell",
        "erlang" => "Erlang",
        "lisp" => "Lisp",
        "sql" => "SQL",
        "bash" => "Bash",
        "powershell" => "PowerShell",
        "assembly" => "Assembly",
        "matlab" => "MATLAB",
        "objective-c" => "Objective-C",
        "groovy" => "Groovy",
        "lua" => "Lua",
        "delphi" => "Delphi",
        "vba" => "VBA",
        "visual_basic" => "Visual Basic",
        "cobol" => "COBOL",
        "fortran" => "Fortran",
        "abap" => "ABAP",
        "pl/sql" => "PL/SQL",
        "scratch" => "Scratch",
    ];

    const ENVIRONMENT = [
        "on-site" => "On-site",
        "hybrid" => "Hybrid",
        "remote" => "Remote",
    ];

    const JOBS = [
        "backend_developer" => "Backend Developer",
        "frontend_developer" => "Frontend Developer",
        "fullstack_developer" => "Fullstack Developer",
        "mobile_app_developer" => "Mobile App Developer",
        "web_designer" => "Web Designer",
        "database_administrator" => "Database Administrator",
        "devops_engineer" => "DevOps Engineer",
        "system_administrator" => "System Administrator",
        "data_scientist" => "Data Scientist",
        "artificial_intelligence_engineer" => "Artificial Intelligence Engineer",
        "game_developer" => "Game Developer",
        "embedded_systems_developer" => "Embedded Systems Developer",
        "ui_ux_designer" => "UI/UX Designer",
        "quality_assurance_tester" => "Quality Assurance Tester",
        "security_expert" => "Security Expert",
        "cloud_computing_engineer" => "Cloud Computing Engineer",
        "blockchain_developer" => "Blockchain Developer",
        "iot_developer" => "IoT Developer",
        "big_data_engineer" => "Big Data Engineer",
        "ethical_hacker" => "Ethical Hacker",
        "project_manager" => "Project Manager",
        "product_manager" => "Product Manager",
        "business_analyst" => "Business Analyst",
        "technical_writer" => "Technical Writer",
        "technical_support_engineer" => "Technical Support Engineer",
        "sales_engineer" => "Sales Engineer",
        "data_analyst" => "Data Analyst",
    ];

    const OTHER = [
        "DevOps" => "DevOps",
        "kubernetes" => "Kubernetes",
        "docker" => "Docker",
        "aws" => "AWS",
        "azure" => "Azure",
        "gcp" => "GCP",
        "firebase" => "Firebase",
        "git" => "Git",
        "github" => "GitHub",
        "gitlab" => "GitLab",
        "bitbucket" => "Bitbucket",
        "jira" => "Jira",
        "confluence" => "Confluence",
        "slack" => "Slack",
        "linux" => "Linux",
        "windows" => "Windows",
        "macos" => "macOS",
        "android" => "Android",
        "ios" => "iOS",
        "raspberry_pi" => "Raspberry Pi",
        "wordpress" => "WordPress",
        "drupal" => "Drupal",
        "joomla" => "Joomla",
        "magento" => "Magento",
        "shopify" => "Shopify",
        "woocommerce" => "WooCommerce",
        "prestashop" => "PrestaShop",
        "wix" => "Wix",
        "squarespace" => "Squarespace",
        "weebly" => "Weebly",
        "webflow" => "Webflow",
        "facebook_ads" => "Facebook Ads",
    ];

    const GOOGLE = [
        "google_analytics" => "Google Analytics",
        "google_ads" => "Google Ads",
        "google_tag_manager" => "Google Tag Manager",
        "google_search_console" => "Google Search Console",
        "google_optimize" => "Google Optimize",
        "google_data_studio" => "Google Data Studio",
        "google_my_business" => "Google My Business",
        "google_maps" => "Google Maps",
        "google_drive" => "Google Drive",
        "google_docs" => "Google Docs",
        "google_sheets" => "Google Sheets",
        "google_slides" => "Google Slides",
        "google_forms" => "Google Forms",
        "google_calendar" => "Google Calendar",
        "google_translate" => "Google Translate",
        "google_photos" => "Google Photos",
        "google_keep" => "Google Keep",
        "google_cloud" => "Google Cloud",
        "google_fonts" => "Google Fonts"
    ];

    const AWS = [
        "aws_ec2" => "AWS EC2",
        "aws_lambda" => "AWS Lambda",
        "aws_s3" => "AWS S3",
        "aws_rds" => "AWS RDS",
        "aws_dynamodb" => "AWS DynamoDB",
        "aws_cloudfront" => "AWS CloudFront",
        "aws_elastic_beanstalk" => "AWS Elastic Beanstalk",
        "aws_route_53" => "AWS Route 53",
        "aws_cloudwatch" => "AWS CloudWatch",
        "aws_cloudformation" => "AWS CloudFormation",
        "aws_elasticache" => "AWS ElastiCache",
        "aws_ecs" => "AWS ECS",
        "aws_ebs" => "AWS EBS",
    ];

    public static function getYears(): array
    {
        $years = range(1920, (int)date("Y"));
        rsort($years);
        return $years;
    }

    public static function getMonths(): array
    {
        $currentYear = (int)date("Y");
        $months = [];
        for ($i = 1; $i <= 12; $i++) {
            $month = new DateTime();
            $month->setDate($currentYear, $i, 1);
            $months[$i] = $month->format("F");
        }
        return $months;
    }

    public static function getWorldStates(): array
    {
        return array_merge(
            self::NORTH_AMERICAN_STATES,
            self::SOUTH_AMERICAN_STATES,
            self::EUROPEAN_STATES,
            self::AFRICAN_STATES,
            self::ASIAN_STATES,
            self::AUSTRALIAN_STATES
        );
    }

    public static function getValidValues(): array
    {
        return array_merge(
            self::LANGUAGES,
            self::FRONTEND_FRAMEWORKS,
            self::BACKEND_FRAMEWORKS,
            self::GOOGLE,
            self::AWS,
            self::OTHER
        );
    }
}
